Facter.add("zabbix_file_headers") do
	result = <<-EOF
# This file is managed by puppet.
# This file is being managed by the puppet-zabbix module.
# Do not edit this file.
# Changes to this file will overwritten in the next puppet run.
# This header is defined in zabbix_file_headers Facter
	EOF
	setcode do
		result
	end
end
